//
// Generated file, do not edit! Created by opp_msgtool 6.0 from CustomMessage.msg.
//

#ifndef __CUSTOMMESSAGE_M_H
#define __CUSTOMMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CustomMessage;
/**
 * Class generated from <tt>CustomMessage.msg:1</tt> by opp_msgtool.
 * <pre>
 * message CustomMessage
 * {
 *     string content;
 *     string otp;
 * }
 * </pre>
 */
class CustomMessage : public ::omnetpp::cMessage
{
  protected:
    omnetpp::opp_string content;
    omnetpp::opp_string otp;

  private:
    void copy(const CustomMessage& other);

  protected:
    bool operator==(const CustomMessage&) = delete;

  public:
    CustomMessage(const char *name=nullptr, short kind=0);
    CustomMessage(const CustomMessage& other);
    virtual ~CustomMessage();
    CustomMessage& operator=(const CustomMessage& other);
    virtual CustomMessage *dup() const override {return new CustomMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getContent() const;
    virtual void setContent(const char * content);

    virtual const char * getOtp() const;
    virtual void setOtp(const char * otp);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CustomMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CustomMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CustomMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<CustomMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CUSTOMMESSAGE_M_H

